import enum


class tokentype():
        function_tok = "function_tok"
        end_tok = "end_tok"
        if_tok = "if_tok"
        else_tok = "else_tok"
        print_tok = "print_tok"
        for_tok = "for_tok"
        while_tok = "while_tok"
        le_operator = "le_operator"
        lt_operator = "lt_operator"
        ge_operator = "ge_operator"
        gt_operator = "gt_operator"
        ne_operator = "ne_operator"
        eq_operator = "eq_operator"
        assignment_operator = "assignment_operator"
        add_operator = "add_operator"
        add_operator = "add_operator"
        mul_operator = "mul_operator"
        mod_operator = "mod_operator"
        exp_operator = " exp_operator "
        left_parent = "left_parent"
        right_parent = "right_parent"
        colon_tok = "colon_tok"
        EOS_TOK= "EOS_TOK"
        literal_integer = "literal_integer"
        id = "id"
